### ISSUE TITLE
Exalta Launcher is broken with most recent versions of ROTMG

### ISSUE THREAD

**Issue by long0900** [amydevs/exalta-launcher#2]
It seems that it failed to log in due to some changes on ROTMG side.
Here are some descriptions about the errors when I click "log in":
![image](https://github.com/amydevs/exalta-launcher/assets/38281050/c664d9e7-1344-47ef-bef2-2faeb3c9b4f0)
![image](https://github.com/amydevs/exalta-launcher/assets/38281050/b06dc959-df3c-4df5-a585-f36301107c04)
![image](https://github.com/amydevs/exalta-launcher/assets/38281050/6bd854ad-1a5b-41f6-8cb8-af9aeb4938bb)
![image](https://github.com/amydevs/exalta-launcher/assets/38281050/ca3a2b9e-8300-44ea-b9b5-3dd4dd0c48a0)
![image](https://github.com/amydevs/exalta-launcher/assets/38281050/1f962e10-d648-480c-843a-43c32856d5f3)

**Comment by amydevs** [comment]
Hi, haven't played ROTMG in a long while, but i'll take a look when i get the time

**Comment by amydevs** [comment]
This was caused by the devs disabling GZIP and Deflate on API routes, despite the official client still sending the accept encoding header with GZIP and Deflate.

I've made a new release to fix this:

https://github.com/amydevs/exalta-launcher/releases/tag/0.4.4

**Comment by amydevs** [comment]
@long0900 fixed! ty for the bug report
